#!/bin/sh

toggleAllFiles() {
  case $1 in
    show )
    defaults write com.apple.finder AppleShowAllFiles Yes && killall Finder
    echo "macOS, naked."
    break;;

    hide)
    defaults write com.apple.finder AppleShowAllFiles No && killall Finder
    echo "Clothes on."
    break;;

    fuck)
    killall Finder
    echo "Fuck Finder."
    break;;

    *)
    echo "Alright then."
    break;;
  esac
}

toggleAllFiles $@
