#!/bin/sh

toggleAppleFontSmoothing() {
  case $1 in
  enable )
  defaults write -g AppleFontSmoothing -int 1
  echo "LCD Font Smoothing Enabled"
  break;;

  disable )
  defaults write -g AppleFontSmoothing -int 0
  echo "LCD Font Smoothing Disabled"
  break;;

  *)
  echo "What! What do you want!"
  esac
}

toggleAppleFontSmoothing $@

killall Finder
killall Dock
